#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'chef-solo-search'
cookbook 'users'
cookbook 'sudo'
cookbook 'openssh'
cookbook 'nginx'
cookbook 'rvm', git: 'https://github.com/martinisoft/chef-rvm.git'
cookbook 'postgresql', git: 'https://github.com/phlipper/chef-postgresql.git'
cookbook 'nodejs', '~> 2.4.2'
cookbook 'ufw', git: 'https://github.com/lukyanovfedor/ufw.git'
cookbook 'imagemagick'
cookbook 'monit'
